'use strict';
const el = id => document.getElementById(id);
const number = value => new Intl.NumberFormat('en-GB').format(value);
const labels = {matched:'Matched',no_swap_in_loaded_data:'No loaded swap',no_successful_swap_in_loaded_data:'No successful swap',missing_wallet_transaction_id:'Missing reference',ambiguous_transaction_id:'Duplicate reference',missing_amount:'Missing amount',amount_mismatch:'Amount difference',payment_method_needs_review:'Payment method',customer_lookup_unavailable:'Customer lookup unavailable',customer_lookup_differs:'Customer differs',wallet_not_loaded:'Wallet not loaded',customer_not_available:'Customer not available',currency_unavailable:'Currency unavailable',timestamp_unavailable:'Timestamp unavailable',after_observed_swap_cutoff:'After observed swap cutoff',before_observed_swap_start:'Before observed swap start',within_observed_swap_span:'Within observed swap dates',no_swap_data_loaded:'No swap dates loaded'};
const state = {filters:{},summary:null,page:null,cursors:[null],index:0,reviewOnly:true,busy:false,failed:false,selected:null,returnFocus:null};
function node(tag, className, text){ const n=document.createElement(tag); if(className)n.className=className; if(text!==undefined)n.textContent=text; return n; }
function money(value){ if(value===null||value===undefined)return '—'; const [whole,decimal]=String(value).split('.'); return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(decimal!==undefined?'.'+decimal:''); }
function sourceTime(value){ if(!value)return 'Unavailable'; return value.replace('T',' ').slice(0,19); }
function badge(record){ const b=node('span','badge'+(!record.needs_review?' good':'')); b.append(node('span','badge-dot'),node('span','',record.reconciliation_status==='matched'&&record.needs_review?'Matched · review':labels[record.reconciliation_status]||record.reconciliation_status)); return b; }
function params(includePage=false){ const q=new URLSearchParams(state.filters); if(includePage){q.set('review_only',String(state.reviewOnly));q.set('limit','50');if(state.cursors[state.index])q.set('cursor',state.cursors[state.index]);} return q; }
async function api(path){ const response=await fetch(path,{cache:'no-store'}); const data=await response.json(); if(!response.ok)throw new Error(data.error||'The request could not be completed.'); return data; }
function busy(value){state.busy=value;document.body.classList.toggle('loading',value);for(const id of ['apply','reset','review-only','country','start','end','status'])el(id).disabled=value;el('export').disabled=value||state.failed;el('previous').disabled=value||state.failed||state.index===0;el('next').disabled=value||state.failed||!state.page?.has_more;el('rows').setAttribute('aria-busy',String(value));}
function error(message){el('error').hidden=!message;el('error').textContent=message||'';}
function renderSummary(){
  const s=state.summary; el('total').textContent=number(s.deduction_count);el('matched').textContent=number(s.groups.filter(g=>g.status==='matched').reduce((sum,g)=>sum+g.deduction_count,0));el('review').textContent=number(s.needs_review_count);el('unmatched').textContent=number(s.groups.filter(g=>g.status==='no_swap_in_loaded_data').reduce((sum,g)=>sum+g.deduction_count,0));
  const countries=new Map(); for(const g of s.groups){if(!countries.has(g.country))countries.set(g.country,{total:0,matched:0,review:0,currencies:new Set()});const c=countries.get(g.country);c.total+=g.deduction_count;c.review+=g.needs_review_count;if(g.status==='matched')c.matched+=g.deduction_count;c.currencies.add(g.currency||'Unknown currency');}
  el('countries').replaceChildren(); if(!countries.size){el('countries').append(node('div','country-placeholder','No deductions match the selected filters.'));return;}
  for(const [name,c] of countries){const card=node('article','country-card');const top=node('div','country-top');top.append(node('span','country-icon',name==='Kenya'?'KE':'RW'));const title=node('div');title.append(node('h3','',name),node('div','currency-label',Array.from(c.currencies).join(' · ')));top.append(title);const rate=node('div','rate',(100*c.matched/c.total).toFixed(2)+'%');rate.append(node('span','','matched'));top.append(rate);const track=node('div','progress-track');const fill=node('div','progress-good');fill.style.width=(100*c.matched/c.total)+'%';track.append(fill);const stats=node('div','country-stats');for(const [label,count]of [['Deductions',c.total],['Matched',c.matched],['Review',c.review]]){const text=node('span','',label+' ');text.append(node('b','',number(count)));stats.append(text);}card.append(top,track,stats);el('countries').append(card);}
}
function renderRows(){
  const records=state.page.records;el('rows').replaceChildren(); const total=state.reviewOnly?state.summary.needs_review_count:state.summary.deduction_count;el('case-count').textContent=number(total);el('table-caption').textContent=state.reviewOnly?'Unmatched deductions and matched records with additional review flags.':'All deductions matching your country, date and result filters.';
  if(!records.length){const tr=node('tr');const td=node('td','empty-state','No transactions match these filters. Try a different country or date range.');td.colSpan=7;tr.append(td);el('rows').append(tr);}
  for(const r of records){const tr=node('tr');const customer=node('td');customer.append(node('div','customer-name',r.wallet_customer_name||'Customer unavailable'),node('div','cell-sub',r.wallet_customer_reference||r.wallet_code||'No customer reference'));const country=node('td');country.append(node('span','country-chip',r.country||'Unknown'));const ref=node('td');const primary=node('div','reference',r.wallet_reference||r.transaction_id||'Missing reference');primary.title=r.wallet_reference||r.transaction_id||'';ref.append(primary,node('div','cell-sub',r.transaction_id||'No Transaction ID'));const amount=node('td','amount-column');amount.append(node('span','amount',money(r.wallet_amount)),node('span','amount-currency',r.wallet_currency||'?'));const result=node('td');result.append(badge(r));const extraReasons=r.review_reasons.filter(value=>value!==r.reconciliation_status);if(extraReasons.length){const reason=node('div','reason-sub',extraReasons.map(v=>labels[v]||v.replaceAll('_',' ')).join(' · '));reason.title=reason.textContent;result.append(reason);}const date=node('td','',sourceTime(r.wallet_created_on));const action=node('td');const open=node('button','open-button','View ↗');open.setAttribute('aria-label','View transaction '+(r.wallet_reference||r.wallet_record_id));open.addEventListener('click',()=>openDetail(r));action.append(open);tr.append(customer,country,ref,amount,result,date,action);el('rows').append(tr);}
  const from=records.length?state.index*50+1:0;const to=records.length?state.index*50+records.length:0;el('page-info').textContent=`Showing ${number(from)}–${number(to)} of ${number(total)}`;el('previous').disabled=state.index===0;el('next').disabled=!state.page.has_more;
}
async function load(all=true){if(state.busy){state.refreshPending=true;return;}busy(true);error();try{const data=await api((all?'/api/dashboard?':'/api/records?')+params(true));if(all){state.summary=data.summary;renderSummary();}state.failed=false;state.page=data.page;renderRows();el('updated').textContent='Refreshed '+new Date(data.generated_at_utc).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){state.failed=true;state.page=null;error(e.message);el('updated').textContent='Refresh failed';for(const id of ['total','matched','review','unmatched','case-count'])el(id).textContent='—';el('countries').replaceChildren(node('div','country-placeholder','Results are unavailable. Apply filters again to retry.'));const tr=node('tr');const td=node('td','empty-state','The results could not be loaded. Please retry.');td.colSpan=7;tr.append(td);el('rows').replaceChildren(tr);el('page-info').textContent='Results unavailable';}finally{busy(false);if(state.refreshPending){state.refreshPending=false;load();}}}
function readFilters(){const filters={};for(const id of ['country','start','end','status'])if(el(id).value)filters[id]=el(id).value;return filters;}
el('filters').addEventListener('submit',event=>{event.preventDefault();const filters=readFilters();if(filters.start&&filters.end&&filters.start>filters.end){error('The from date must not be after the through date.');return;}state.filters=filters;state.cursors=[null];state.index=0;load();});
el('reset').addEventListener('click',()=>{HTMLFormElement.prototype.reset.call(el('filters'));el('review-only').checked=true;state.reviewOnly=true;state.filters={};state.cursors=[null];state.index=0;load();});
el('review-only').addEventListener('change',()=>{state.reviewOnly=el('review-only').checked;state.cursors=[null];state.index=0;load();});
el('next').addEventListener('click',()=>{if(state.busy||!state.page?.has_more)return;state.cursors[state.index+1]=state.page.next_cursor;state.index++;load(false);});
el('previous').addEventListener('click',()=>{if(state.busy||!state.index)return;state.index--;load(false);});
function field(grid,label,value){grid.append(node('dt','',label),node('dd','',Array.isArray(value)?value.join(', '):(value??'Unavailable')));}
async function openDetail(record){
  state.returnFocus=document.activeElement;state.selected=record;el('drawer').hidden=false;el('drawer-overlay').hidden=false;el('drawer-content').replaceChildren(node('p','','Loading transaction details…'));el('close-drawer').focus();
  try{const data=await api('/api/detail?'+new URLSearchParams({record_id:record.wallet_record_id,country:record.country}));if(state.selected!==record)return;const r=data.record;const body=el('drawer-content');body.replaceChildren(node('h2','',r.wallet_customer_name||'Transaction details'),badge(r));const reasons=node('div','reason-list');for(const reason of r.review_reasons.filter(value=>value!==r.reconciliation_status))reasons.append(node('span','badge',labels[reason]||reason.replaceAll('_',' ')));body.append(reasons);
    let grid=node('dl','detail-grid');field(grid,'Country',r.country);field(grid,'Customer reference',r.wallet_customer_reference);field(grid,'Customer lookup',r.wallet_customer_id);field(grid,'Wallet',r.wallet_code||r.wallet_id);body.append(node('h3','','Customer & wallet'),grid);
    grid=node('dl','detail-grid');field(grid,'Reference',r.wallet_reference);field(grid,'Transaction ID',r.transaction_id);field(grid,'Record ID',r.wallet_record_id);field(grid,'Amount',money(r.wallet_amount)+' '+(r.wallet_currency||''));field(grid,'Created on',sourceTime(r.wallet_created_on));field(grid,'Deductions sharing reference',r.wallet_count);body.append(node('h3','','Wallet deduction'),grid);
    grid=node('dl','detail-grid');field(grid,'Loaded swaps',r.swap_count);field(grid,'Successful swaps',r.successful_swap_count);field(grid,'Successful swap amount',money(r.successful_swap_amount));field(grid,'Successful swap created',sourceTime(r.successful_swap_created_on));field(grid,'Swap references',r.swap_references?.length?r.swap_references:null);field(grid,'Payment methods',r.successful_payment_methods?.length?r.successful_payment_methods:null);field(grid,'Customer comparison',r.swap_customer_lookup_check.replaceAll('_',' '));body.append(node('h3','','Swap comparison'),grid);
    grid=node('dl','detail-grid');field(grid,'Date context',labels[r.coverage_assessment]||r.coverage_assessment);field(grid,'Observed swap start',sourceTime(r.observed_first_swap));field(grid,'Observed swap end',sourceTime(r.observed_last_swap));body.append(node('h3','','Source coverage'),grid,node('p','detail-note','Review flags indicate records to investigate. Export coverage and refund eligibility have not been verified. Customer details and currency reflect the current wallet snapshot.'));
  }catch(e){if(state.selected===record)el('drawer-content').replaceChildren(node('p','error-banner',e.message));}
}
function closeDetail(){state.selected=null;el('drawer').hidden=true;el('drawer-overlay').hidden=true;state.returnFocus?.focus({preventScroll:true});}
el('close-drawer').addEventListener('click',closeDetail);el('drawer-overlay').addEventListener('click',closeDetail);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDetail();if(event.key==='Tab'&&!el('drawer').hidden){event.preventDefault();el('close-drawer').focus();}});
el('export').addEventListener('click',async()=>{if(state.busy)return;busy(true);error();el('export').textContent='Exporting…';try{const response=await fetch('/api/export?'+params());if(!response.ok){const data=await response.json();throw new Error(data.error||'Export failed.');}const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download='spiro_review_candidates.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}finally{el('export').textContent='↓ Export candidates';busy(false);}});
load();

document.addEventListener('data-imported', () => {state.cursors=[null];state.index=0;load();});
