(() => {
'use strict';
const el = id => document.getElementById(id);
const panel = el('import-panel');
if (!panel) return;
const payments = panel.dataset.scope === 'payments';
const swaps = panel.dataset.scope === 'swap-payments';
const sourceEndpoint = swaps ? '/api/swap-sources' : payments ? '/api/payments-sources' : '/api/sources';
const uploadEndpoint = swaps ? '/api/swap-uploads' : payments ? '/api/payments-uploads' : '/api/uploads';
const jobEndpoint = swaps ? '/api/swap-import-jobs/' : payments ? '/api/payments-import-jobs/' : '/api/import-jobs/';
const datasets = swaps ? [['swap_payments','Swap payments'],['swap','Swapping transactions']] : payments ? [['atlas','Atlas payments'],['wallet','Wallet transactions']] : [['wallet_master','Wallets'],['wallet','Wallet transactions'],['swap','Swapping transactions']];
const number = value => new Intl.NumberFormat('en-GB').format(value);
function node(tag, className, text) { const n = document.createElement(tag); if(className) n.className=className; if(text!==undefined) n.textContent=text; return n; }
function sourceTime(value) { return value ? value.replace('T',' ').slice(0,19) : 'Unavailable'; }
async function api(path) { const response=await fetch(path,{cache:'no-store'}); const data=await response.json(); if(!response.ok) throw new Error(data.error || 'The request could not be completed.'); return data; }
const uploads = {token:null,maxBytes:512*1024*1024,busy:false,jobs:[]};
function uploadError(message){el('upload-error').hidden=!message;el('upload-error').textContent=message||'';}
function uploadControls(){el('upload-files').disabled=uploads.busy;el('validate-files').disabled=uploads.busy||!uploads.token||!el('upload-files').files.length||uploads.jobs.length>0;el('import-files').disabled=uploads.busy||!uploads.jobs.some(job=>job.state==='ready');el('clear-files').disabled=uploads.busy||(!uploads.jobs.length&&!el('upload-files').files.length);}
async function importAction(path,body,headers={}){const response=await fetch(path,{method:'POST',headers:{'X-Spiro-Token':uploads.token,...headers},body});const data=await response.json();if(!response.ok){const failure=new Error(data.error||'The import request failed.');failure.status=response.status;throw failure;}return data;}
function renderJobs(){el('upload-jobs').replaceChildren();for(const job of uploads.jobs){const card=node('article','upload-card');const head=node('div','upload-card-head');head.append(node('strong','upload-filename',job.filename),node('span','upload-state '+job.state,job.state==='ready'?'Validated':job.state==='complete'?'Imported':job.state==='failed'?'Failed':job.phase||job.state));card.append(head);if(job.preview){const p=job.preview;card.append(node('div','upload-meta',p.module+' · '+Object.entries(p.countries).map(([country,count])=>country+' '+number(count)).join(' · ')+' · '+number(p.rows)+' rows'));card.append(node('div','upload-dates','Created: '+sourceTime(p.min_created_on)+' → '+sourceTime(p.max_created_on)));if(p.duplicate_record_id_rows)card.append(node('p','upload-warning',number(p.duplicate_record_id_rows)+' repeated Record Id rows. The latest source version is kept.'));if(p.export_cap_warning)card.append(node('p','upload-warning','This file may be at the Zoho export limit. Add the remaining date batches to complete coverage.'));}if(job.result)card.append(node('p','upload-result',number(job.result.rows_read)+' rows read · '+number(job.result.rows_applied)+' records added or updated'+(job.result.rows_applied===0?' · Already loaded or older than the current data.':'')));else if(job.processed_rows)card.append(node('p','upload-progress',number(job.processed_rows)+' rows processed'));if(job.error)card.append(node('p','upload-failure',job.error));el('upload-jobs').append(card);}uploadControls();}
async function waitForImport(job){while(['receiving','validating','importing'].includes(job.state)){await new Promise(resolve=>setTimeout(resolve,1000));const update=await api(jobEndpoint+job.id);Object.assign(job,update);renderJobs();}return job;}
async function loadSources(){try{const data=await api(sourceEndpoint);el('source-inventory').replaceChildren();for(const [dataset,title]of datasets){const card=node('article','source-card');card.append(node('h3','',title));const rows=data.sources.filter(row=>row.dataset===dataset);if(!rows.length)card.append(node('p','','No data loaded'));for(const row of rows){const line=node('div','source-count');line.append(node('span','',row.country||'Unknown country'),node('strong','',number(row.rows)));card.append(line);}el('source-inventory').append(card);}el('import-history').replaceChildren();if(!data.recent_imports.length)el('import-history').append(node('p','','No imports yet. Add your first export above.'));for(const batch of data.recent_imports){const line=node('div','history-row');const title=node('div');title.append(node('strong','',batch.filename),node('span','',batch.module+' · '+new Date(batch.imported_at).toLocaleString()));line.append(title,node('span','',number(batch.rows_read)+' read / '+number(batch.rows_applied)+' changed'));el('import-history').append(line);}}catch(e){el('source-inventory').replaceChildren(node('p','upload-failure',e.message));}}
el('upload-files').addEventListener('change',()=>{uploadError();uploadControls();el('upload-message').textContent=el('upload-files').files.length?el('upload-files').files.length+' file(s) selected. Validate them before importing.':'';});
el('validate-files').addEventListener('click',async()=>{const files=Array.from(el('upload-files').files);uploadError();if(!files.length)return;if(files.length>10){uploadError('Choose up to 10 files at a time.');return;}if(files.some(file=>!file.name.toLowerCase().endsWith('.csv')||!file.size||file.size>uploads.maxBytes)){uploadError('Choose nonempty CSV files up to 512 MB each.');return;}uploads.busy=true;uploadControls();try{for(const file of files){el('upload-message').textContent='Uploading and validating '+file.name+'…';const job=await importAction(uploadEndpoint,file,{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name)});uploads.jobs.push(job);renderJobs();await waitForImport(job);}const ready=uploads.jobs.filter(job=>job.state==='ready').length;el('upload-message').textContent=ready?ready+' file(s) validated. Review the details below, then click Import validated files.':'No files passed validation. Clear the list and choose a corrected export.';}catch(e){uploadError(e.message);el('upload-message').textContent='Validation stopped. Completed file checks are shown below.';}finally{uploads.busy=false;renderJobs();}});
el('import-files').addEventListener('click',async()=>{uploads.busy=true;uploadControls();uploadError();const order={swap_payments:0,atlas:0,wallet_master:0,wallet:1,swap:2};const ready=uploads.jobs.filter(job=>job.state==='ready').sort((a,b)=>order[a.preview.dataset]-order[b.preview.dataset]);let imported=0;try{for(const job of ready){el('upload-message').textContent='Importing '+job.filename+'…';Object.assign(job,await importAction(jobEndpoint+job.id+'/commit'));renderJobs();await waitForImport(job);if(job.state!=='complete')throw new Error(job.error||'Import failed.');imported++;}el('upload-message').textContent=imported+' file(s) imported. Reconciliation results refresh automatically below.';}catch(e){uploadError(e.message);el('upload-message').textContent=imported+' file(s) confirmed imported. Earlier completed files are saved. Check Recent imports if the connection was interrupted.';}finally{uploads.busy=false;renderJobs();await loadSources();if(imported){document.dispatchEvent(new Event('data-imported'));}}});
el('clear-files').addEventListener('click',async()=>{uploads.busy=true;uploadControls();try{for(const job of uploads.jobs){try{await importAction(jobEndpoint+job.id+'/discard');}catch(e){if(e.status!==404)throw e;}}uploads.jobs=[];el('upload-files').value='';el('upload-message').textContent='';uploadError();}catch(e){uploadError(e.message);}finally{uploads.busy=false;renderJobs();}});
el('refresh-sources').addEventListener('click',loadSources);
el('import-panel').addEventListener('toggle',()=>{document.querySelector('.import-open').textContent=el('import-panel').open?'Close ↑':'Open ↓';});
(async()=>{try{const session=await api('/api/session');uploads.token=session.csrf_token;uploads.maxBytes=session.max_upload_bytes;uploadControls();}catch(e){uploadError('File uploads are unavailable. Refresh the dashboard.');}loadSources();})();

})();
