-- Independent storage for Payments vs Swap CSV uploads.
CREATE SCHEMA IF NOT EXISTS swap_reconciliation;

CREATE TABLE IF NOT EXISTS swap_reconciliation.swap_payments (
    "Record Id" text PRIMARY KEY,
    "Atlas Transaction ID" text,
    "Payment Owner.id" text,
    "Payment Owner" text,
    "Created By (System).id" text,
    "Created By (System)" text,
    "Modified By.id" text,
    "Modified By" text,
    "Created Time" text,
    "Modified Time" text,
    "Last Activity Time" text,
    "Currency" text,
    "Tag" text,
    "Unsubscribed Mode" text,
    "Unsubscribed Time" text,
    "Locked" boolean,
    "Payment Operator" text,
    "Created On" text,
    "Last Modified On" text,
    "Created By" text,
    "Last Modified By" text,
    "Transaction Date" text,
    "Settled Against" text,
    "Payment Status" text,
    "Payment Mode" text,
    "Transaction Type" text,
    "Company ID" text,
    "Customer ID" text,
    "Wallet ID" text,
    "External Payment Operator Transaction ID" text,
    "Order No" text,
    "Customer.id" text,
    "Customer" text,
    "Order.id" text,
    "Order" text,
    "Customer's Latest Transaction" text,
    "Payment Transaction No" text,
    "Product ID" text,
    "Page Type" text,
    "Company.id" text,
    "Company" text,
    "Mobile No" text,
    "Amount" text,
    "Job Status" text,
    "Job ID" text,
    "Job Time" text,
    "Remarks" text,
    "Company Name" text,
    "Customer Name" text,
    "Customer Type" text,
    "City" text,
    "Country" text,
    "External ID" text,
    "State" text,
    "Select City.id" text,
    "Select City" text,
    "USSD_mapping" text,
    "Parent_Payment_ID" text,
    "Time" text,
    "Trigger Time" text,
    "Status_Check_Time" text,
    "Push API Log" text,
    "Push API Call Time" text,
    "Refresh API Log" text,
    "Refresh API Call Time" text,
    "Push Time In Sec" text,
    "Refresh Time In Sec" text,
    "Create Time In Sec" text,
    "CF Time" text,
    "Wallet API Count" text,
    "Operator Receipt No" text,
    "Manual Credit" boolean,
    "Connected To.module" text,
    "Connected To.id" text,
    "Union Due ID (Old)" text,
    "App User.id" text,
    "App User" text,
    "Vehicle Reg No" text,
    "Union Due ID (New)" text,
    "Loan ID" text,
    "Change Log Time" text
);

CREATE TABLE IF NOT EXISTS swap_reconciliation.swap_transactions (
    "Record Id" text PRIMARY KEY,
    "Battery Swapping ID" text,
    "Swapping Transaction Owner.id" text,
    "Swapping Transaction Owner" text,
    "Last Activity Time" text,
    "Tag" text,
    "Unsubscribed Mode" text,
    "Unsubscribed Time" text,
    "Locked" boolean,
    "Select City.id" text,
    "Select City" text,
    "Station" text,
    "Customer Name" text,
    "Vehicle ID" text,
    "In Battery OEM No" text,
    "Out Battery OEM No" text,
    "Swap Date" text,
    "State" text,
    "Country" text,
    "Pay Method" text,
    "Status" text,
    "Energy Agent" text,
    "Vehicle 360.id" text,
    "Vehicle 360" text,
    "Customer.id" text,
    "Customer" text,
    "City" text,
    "In Battery OEM 360.id" text,
    "In Battery OEM 360" text,
    "Swap Station.id" text,
    "Swap Station" text,
    "Energy Agents.id" text,
    "Energy Agents" text,
    "Out Battery OEM 360.id" text,
    "Out Battery OEM 360" text,
    "In Battery Serial No" text,
    "Out Battery Serial No" text,
    "Vehicle Reg No" text,
    "Last Modified On" text,
    "External ID" text,
    "Last Modified By" text,
    "Created_By" text,
    "Created On" text,
    "RecordID" text,
    "Transaction Exemption Type" text,
    "Transaction ID" text,
    "Swap Amount" text,
    "Billable SOC" text,
    "Net SOC" text,
    "Non-Billable SOC" text,
    "Out Battery Current SOC" text,
    "In Battery Previous SOC" text,
    "In Battery Current SOC" text,
    "In Battery SOC Scan" text,
    "Out Battery SOC Scan" text,
    "App Version" text,
    "Platform" text,
    "Vcu Status" text,
    "Swap Performed By" text,
    "Market Price (Per SOC)" text,
    "Manual OEM Entered" boolean,
    "Customer Feedback.id" text,
    "Customer Feedback" text,
    "Connected To.module" text,
    "Connected To.id" text,
    "Operational Mode" text,
    "App User.id" text,
    "App User" text,
    "Distributor Commission Amount" text,
    "Franchise Station.id" text,
    "Franchise Station" text,
    "Model" text,
    "Change Log Time" text
);

-- Audit history for uploads into public.swap_payments and public.swap_transactions.
CREATE TABLE IF NOT EXISTS swap_reconciliation.swap_import_batches (
    batch_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dataset text NOT NULL CHECK (dataset IN ('swap_payments','swap')),
    source_file text NOT NULL,
    sha256 text NOT NULL,
    rows_read bigint NOT NULL,
    rows_applied bigint NOT NULL,
    min_created_on timestamp without time zone,
    max_created_on timestamp without time zone,
    imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS swap_payments_atlas_id_idx ON swap_reconciliation.swap_payments ("Atlas Transaction ID");
CREATE INDEX IF NOT EXISTS swap_operator_transaction_id_idx ON swap_reconciliation.swap_transactions ("Transaction ID") WHERE "Pay Method" = 'PAYMENT_OPERATOR';
COMMENT ON SCHEMA swap_reconciliation IS 'Independent Payments vs Swap uploads and history; only PAYMENT_OPERATOR swaps are reconciled.';
