'use strict';
const el = id => document.getElementById(id);
const number = value => new Intl.NumberFormat('en-GB').format(value);
const labels = {matched:'Matched',no_swap_in_loaded_data:'No loaded swap',no_successful_swap_in_loaded_data:'No successful swap',missing_wallet_transaction_id:'Missing reference',ambiguous_transaction_id:'Duplicate reference',missing_amount:'Missing amount',amount_mismatch:'Amount difference',payment_method_needs_review:'Payment method',customer_lookup_unavailable:'Customer lookup unavailable',customer_lookup_differs:'Customer differs',wallet_not_loaded:'Wallet not loaded',customer_not_available:'Customer not available',currency_unavailable:'Currency unavailable',timestamp_unavailable:'Timestamp unavailable',after_observed_swap_cutoff:'After observed swap cutoff',before_observed_swap_start:'Before observed swap start',within_observed_swap_span:'Within observed swap dates',no_swap_data_loaded:'No swap dates loaded'};
const state = {filters:{},summary:null,page:null,cursors:[null],index:0,reviewOnly:true,busy:false,failed:false,selected:null,returnFocus:null};
let currentView='home';
const offers={group:'needs_review',summary:null,page:null,cursors:[null],index:0,busy:false,failed:false,refreshPending:false};
const offerLabels={covered:'Full SOC coverage',no_consumption:'No linked consumption',multiple_consumptions:'Multiple consumptions',duplicate_consumption_reference:'Duplicate consumption reference',no_allocation:'Allocation not loaded',multiple_allocations:'Multiple allocations',swap_not_successful:'Swap not successful',allocation_customer_mismatch:'Allocation customer differs',consumption_customer_mismatch:'Consumption customer differs',currency_mismatch:'Currency unavailable or differs',wrong_consumption_type:'Not a battery swap',unsupported_offer_terms:'Offer terms need review',missing_offer_reference:'Missing offer reference',allocation_status_needs_review:'Allocation status needs review',missing_validity_dates:'Missing validity dates',consumption_date_mismatch:'Consumption date differs',outside_validity_window:'Outside voucher validity',conflicting_expiry_date:'Conflicting expiry date',uncovered_swap_charge:'Swap has a payable charge',soc_coverage_mismatch:'SOC coverage differs',soc_budget_mismatch:'Voucher balance differs',unsupported_discount_terms:'Discount terms need review'};
const offerResolution={resolved_offer:'Cleared by offer',needs_review:'Needs review',wallet_attached:'Wallet attached'};
const tracking={group:'wallet_without_swap',summary:null,page:null,cursors:[null],index:0,busy:false,failed:false,refreshPending:false};
const due={group:'needs_review',summary:null,page:null,cursors:[null],index:0,busy:false,failed:false,refreshPending:false};
const dueGroupInfo={needs_review:'Swaps without wallet deductions that are not cleared by an exact matching Paid Due. Pending, Closed, missing links and discrepancies remain open.',resolved:'Swaps without wallet deductions cleared by a unique exact matching Due marked Paid.',no_due:'No Due with the same country and swap Record Id is loaded.',matched:'Unique Due links with successful swaps and matching customer, amount and available currency.',paid:'Linked Due records marked Paid in the loaded export.',pending:'Linked Due records marked Pending in the loaded export.',closed:'Linked Due records marked Closed. This status does not establish repayment.',awaiting_due_export:'Countries with no loaded Due records. Upload the corresponding Due export to start matching.',all:'All loaded DUE_CREATED swaps, including matched, review and awaiting-export records.'};
const resolutionLabels={resolved_paid_due:'Cleared by Paid Due',pending_due:'Pending Due — open',closed_due_not_paid:'Closed Due — not Paid',wallet_attached:'Wallet debit attached',needs_review:'Needs review'};
const dueResultLabels={ambiguous_swap_currency:'Conflicting wallet currencies',matched:'Matched Due',no_due_in_loaded_data:'No loaded Due',due_data_not_loaded:'Awaiting Due export',multiple_due_records:'Multiple Due records',swap_not_successful:'Swap not successful',missing_customer_id:'Missing customer ID',customer_mismatch:'Customer differs',missing_amount:'Missing amount',amount_mismatch:'Amount differs',missing_due_currency:'Missing Due currency',currency_mismatch:'Currency differs'};
const groupInfo={open_swaps:{title:'Swaps needing review',caption:'Swaps without committed wallet deductions, excluding verified Paid Dues and full offer coverage. Missing identifiers and unpaid or conflicting Dues remain open.'},wallet_without_swap:{title:'Wallet deductions without swaps',caption:'Committed Debit wallet transactions settled against Swap. No swap with the same country and Transaction ID is loaded.'},swap_without_wallet:{title:'Swaps without wallet deductions',caption:'All loaded swap statuses and payment methods. No committed swap debit with the same country and Transaction ID is loaded.'},unmatchable_swaps:{title:'Unmatchable swaps',caption:'Missing Transaction ID or country. A missing wallet deduction cannot be confirmed. Check the payment method before investigating a charge.'},unmatchable_wallets:{title:'Unmatchable deductions',caption:'Committed swap debits missing Transaction ID or country. A missing swap cannot be confirmed.'}};
const gapReasons={no_swap_in_loaded_data:'No loaded swap',no_committed_swap_wallet_debit_in_loaded_data:'No loaded wallet deduction',missing_transaction_id:'Missing Transaction ID',missing_country:'Missing country'};
function node(tag, className, text){ const n=document.createElement(tag); if(className)n.className=className; if(text!==undefined)n.textContent=text; return n; }
function money(value){ if(value===null||value===undefined)return '—'; const [whole,decimal]=String(value).split('.'); return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(decimal!==undefined?'.'+decimal:''); }
function sourceTime(value){ if(!value)return 'Unavailable'; return value.replace('T',' ').slice(0,19); }
function badge(record){ const b=node('span','badge'+(!record.needs_review?' good':'')); b.append(node('span','badge-dot'),node('span','',record.reconciliation_status==='matched'&&record.needs_review?'Matched · review':labels[record.reconciliation_status]||record.reconciliation_status)); return b; }
function params(includePage=false){ const q=new URLSearchParams(state.filters); if(includePage){q.set('review_only',String(state.reviewOnly));q.set('limit','50');if(state.cursors[state.index])q.set('cursor',state.cursors[state.index]);} return q; }
async function api(path){ const response=await fetch(path,{cache:'no-store'}); const data=await response.json(); if(!response.ok)throw new Error(data.error||'The request could not be completed.'); return data; }
function syncControls(){const value=state.busy||tracking.busy||due.busy||offers.busy;document.body.classList.toggle('loading',value);for(const id of ['apply','reset','review-only','country','start','end','status','view-home','view-overview','view-counterparts','view-due','view-offer','refresh-results','overview-open-swaps','overview-paid-dues','overview-offers','gap-group','due-group','offer-group',...Object.keys(groupInfo).map(group=>'group-'+group)])el(id).disabled=value;el('export').disabled=value||state.failed;el('previous').disabled=value||state.failed||state.index===0;el('next').disabled=value||state.failed||!state.page?.has_more;el('gap-export').disabled=value||tracking.failed||!tracking.page;el('gap-previous').disabled=value||tracking.failed||tracking.index===0;el('gap-next').disabled=value||tracking.failed||!tracking.page?.has_more;el('due-export').disabled=value||due.failed||!due.page;el('due-previous').disabled=value||due.failed||due.index===0;el('due-next').disabled=value||due.failed||!due.page?.has_more;el('offer-export').disabled=value||offers.failed||!offers.page;el('offer-previous').disabled=value||offers.failed||offers.index===0;el('offer-next').disabled=value||offers.failed||!offers.page?.has_more;el('offer-rows').setAttribute('aria-busy',String(offers.busy));el('rows').setAttribute('aria-busy',String(state.busy));el('gap-rows').setAttribute('aria-busy',String(tracking.busy));el('due-rows').setAttribute('aria-busy',String(due.busy));}
function busy(value){state.busy=value;syncControls();}
function error(message){el('error').hidden=!message;el('error').textContent=message||'';}
function renderSummary(){
  const s=state.summary; el('total').textContent=number(s.deduction_count);el('matched').textContent=number(s.groups.filter(g=>g.status==='matched').reduce((sum,g)=>sum+g.deduction_count,0));el('review').textContent=number(s.needs_review_count);el('unmatched').textContent=number(s.groups.filter(g=>g.status==='no_swap_in_loaded_data').reduce((sum,g)=>sum+g.deduction_count,0));
  const countries=new Map(); for(const g of s.groups){if(!countries.has(g.country))countries.set(g.country,{total:0,matched:0,review:0,currencies:new Set()});const c=countries.get(g.country);c.total+=g.deduction_count;c.review+=g.needs_review_count;if(g.status==='matched')c.matched+=g.deduction_count;c.currencies.add(g.currency||'Unknown currency');}
  el('countries').replaceChildren(); if(!countries.size){el('countries').append(node('div','country-placeholder','No deductions match the selected filters.'));return;}
  for(const [name,c] of countries){const card=node('article','country-card');const top=node('div','country-top');top.append(node('span','country-icon',name==='Kenya'?'KE':'RW'));const title=node('div');title.append(node('h3','',name),node('div','currency-label',Array.from(c.currencies).join(' · ')));top.append(title);const rate=node('div','rate',(100*c.matched/c.total).toFixed(2)+'%');rate.append(node('span','','matched'));top.append(rate);const track=node('div','progress-track');const fill=node('div','progress-good');fill.style.width=(100*c.matched/c.total)+'%';track.append(fill);const stats=node('div','country-stats');for(const [label,count]of [['Deductions',c.total],['Matched',c.matched],['Review',c.review]]){const text=node('span','',label+' ');text.append(node('b','',number(count)));stats.append(text);}card.append(top,track,stats);el('countries').append(card);}
}
function renderSwapReview(s){if(s&&s.resolved_offer_count===undefined)throw new Error('Stop the current PyCharm run and run main.py again to activate offer resolutions.');el('swap-review-open').textContent=s?number(s.open_count):'—';el('swap-review-resolved').textContent=s?number(s.resolved_paid_due_count):'—';el('swap-review-offers').textContent=s?number(s.resolved_offer_count):'—';el('swap-review-countries').textContent=s?s.by_country.map(g=>g.country+': '+number(g.open_count)+' open · '+number(g.resolved_paid_due_count)+' Paid Dues · '+number(g.resolved_offer_count)+' offers cleared').join(' | ')||'No swaps without wallet deductions match these filters.':'Restart main.py to load offer resolutions.';}

function renderRows(){
  const records=state.page.records;el('rows').replaceChildren(); const total=state.reviewOnly?state.summary.needs_review_count:state.summary.deduction_count;el('case-count').textContent=number(total);el('table-caption').textContent=state.reviewOnly?'Unmatched deductions and matched records with additional review flags.':'All deductions matching your country, date and result filters.';
  if(!records.length){const tr=node('tr');const td=node('td','empty-state','No transactions match these filters. Try a different country or date range.');td.colSpan=7;tr.append(td);el('rows').append(tr);}
  for(const r of records){const tr=node('tr');const customer=node('td');customer.append(node('div','customer-name',r.wallet_customer_name||'Customer unavailable'),node('div','cell-sub',r.wallet_customer_reference||r.wallet_code||'No customer reference'));const country=node('td');country.append(node('span','country-chip',r.country||'Unknown'));const ref=node('td');const primary=node('div','reference',r.wallet_reference||r.transaction_id||'Missing reference');primary.title=r.wallet_reference||r.transaction_id||'';ref.append(primary,node('div','cell-sub',r.transaction_id||'No Transaction ID'));const amount=node('td','amount-column');amount.append(node('span','amount',money(r.wallet_amount)),node('span','amount-currency',r.wallet_currency||'?'));const result=node('td');result.append(badge(r));const extraReasons=r.review_reasons.filter(value=>value!==r.reconciliation_status);if(extraReasons.length){const reason=node('div','reason-sub',extraReasons.map(v=>labels[v]||v.replaceAll('_',' ')).join(' · '));reason.title=reason.textContent;result.append(reason);}const date=node('td','',sourceTime(r.wallet_created_on));const action=node('td');const open=node('button','open-button','View ↗');open.setAttribute('aria-label','View transaction '+(r.wallet_reference||r.wallet_record_id));open.addEventListener('click',()=>openDetail(r));action.append(open);tr.append(customer,country,ref,amount,result,date,action);el('rows').append(tr);}
  const from=records.length?state.index*50+1:0;const to=records.length?state.index*50+records.length:0;el('page-info').textContent=`Showing ${number(from)}–${number(to)} of ${number(total)}`;el('previous').disabled=state.index===0;el('next').disabled=!state.page.has_more;
}
async function load(all=true){if(state.busy){state.refreshPending=true;return;}busy(true);error();try{const data=await api((all?'/api/dashboard?':'/api/records?')+params(true));if(all){state.summary=data.summary;renderSummary();renderSwapReview(data.swap_review);}state.failed=false;state.page=data.page;renderRows();el('updated').textContent='Refreshed '+new Date(data.generated_at_utc).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){state.failed=true;state.page=null;renderSwapReview();error(e.message);el('updated').textContent='Refresh failed';for(const id of ['total','matched','review','unmatched','case-count'])el(id).textContent='—';el('countries').replaceChildren(node('div','country-placeholder','Results are unavailable. Apply filters again to retry.'));const tr=node('tr');const td=node('td','empty-state','The results could not be loaded. Please retry.');td.colSpan=7;tr.append(td);el('rows').replaceChildren(tr);el('page-info').textContent='Results unavailable';}finally{busy(false);if(state.refreshPending){state.refreshPending=false;load();}}}
function readFilters(){const filters={};for(const id of ['country','start','end','status'])if(el(id).value)filters[id]=el(id).value;return filters;}
function resetPages(){state.cursors=[null];state.index=0;tracking.cursors=[null];tracking.index=0;due.cursors=[null];due.index=0;offers.cursors=[null];offers.index=0;}
function loadActive(){if(currentView==='home')return;if(currentView==='counterparts')return loadTracking();if(currentView==='due')return loadDue();if(currentView==='offer')return loadOffers();return load();}
el('filters').addEventListener('submit',event=>{event.preventDefault();const filters=readFilters();if(currentView!=='overview')delete filters.status;if(filters.start&&filters.end&&filters.start>filters.end){error('The from date must not be after the through date.');return;}state.filters=filters;resetPages();loadActive();});
el('reset').addEventListener('click',()=>{HTMLFormElement.prototype.reset.call(el('filters'));el('review-only').checked=true;state.reviewOnly=true;state.filters={};resetPages();loadActive();});
el('review-only').addEventListener('change',()=>{state.reviewOnly=el('review-only').checked;state.cursors=[null];state.index=0;load();});
el('next').addEventListener('click',()=>{if(state.busy||!state.page?.has_more)return;state.cursors[state.index+1]=state.page.next_cursor;state.index++;load(false);});
el('previous').addEventListener('click',()=>{if(state.busy||!state.index)return;state.index--;load(false);});
function field(grid,label,value){grid.append(node('dt','',label),node('dd','',Array.isArray(value)?value.join(', '):(value??'Unavailable')));}
async function openDetail(record){
  state.returnFocus=document.activeElement;state.selected=record;el('drawer').hidden=false;el('drawer-overlay').hidden=false;el('drawer-content').replaceChildren(node('p','','Loading transaction details…'));el('close-drawer').focus();
  try{const data=await api('/api/detail?'+new URLSearchParams({record_id:record.wallet_record_id,country:record.country}));if(state.selected!==record)return;const r=data.record;const body=el('drawer-content');body.replaceChildren(node('h2','',r.wallet_customer_name||'Transaction details'),badge(r));const reasons=node('div','reason-list');for(const reason of r.review_reasons.filter(value=>value!==r.reconciliation_status))reasons.append(node('span','badge',labels[reason]||reason.replaceAll('_',' ')));body.append(reasons);
    let grid=node('dl','detail-grid');field(grid,'Country',r.country);field(grid,'Customer reference',r.wallet_customer_reference);field(grid,'Customer lookup',r.wallet_customer_id);field(grid,'Wallet',r.wallet_code||r.wallet_id);body.append(node('h3','','Customer & wallet'),grid);
    grid=node('dl','detail-grid');field(grid,'Reference',r.wallet_reference);field(grid,'Transaction ID',r.transaction_id);field(grid,'Record ID',r.wallet_record_id);field(grid,'Amount',money(r.wallet_amount)+' '+(r.wallet_currency||''));field(grid,'Created on',sourceTime(r.wallet_created_on));field(grid,'Deductions sharing reference',r.wallet_count);body.append(node('h3','','Wallet deduction'),grid);
    grid=node('dl','detail-grid');field(grid,'Loaded swaps',r.swap_count);field(grid,'Successful swaps',r.successful_swap_count);field(grid,'Successful swap amount',money(r.successful_swap_amount));field(grid,'Successful swap created',sourceTime(r.successful_swap_created_on));field(grid,'Swap references',r.swap_references?.length?r.swap_references:null);field(grid,'Payment methods',r.successful_payment_methods?.length?r.successful_payment_methods:null);field(grid,'Customer comparison',r.swap_customer_lookup_check.replaceAll('_',' '));body.append(node('h3','','Swap comparison'),grid);
    grid=node('dl','detail-grid');field(grid,'Date context',labels[r.coverage_assessment]||r.coverage_assessment);field(grid,'Observed swap start',sourceTime(r.observed_first_swap));field(grid,'Observed swap end',sourceTime(r.observed_last_swap));body.append(node('h3','','Source coverage'),grid,node('p','detail-note','Review flags indicate records to investigate. Export coverage and refund eligibility have not been verified. Customer details and currency reflect the current wallet snapshot.'));
  }catch(e){if(state.selected===record)el('drawer-content').replaceChildren(node('p','error-banner',e.message));}
}
function closeDetail(){state.selected=null;el('drawer').hidden=true;el('drawer-overlay').hidden=true;state.returnFocus?.focus({preventScroll:true});}
el('close-drawer').addEventListener('click',closeDetail);el('drawer-overlay').addEventListener('click',closeDetail);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDetail();if(event.key==='Tab'&&!el('drawer').hidden){event.preventDefault();el('close-drawer').focus();}});
el('export').addEventListener('click',async()=>{if(state.busy)return;busy(true);error();el('export').textContent='Exporting…';try{const response=await fetch('/api/export?'+params());if(!response.ok){const data=await response.json();throw new Error(data.error||'Export failed.');}const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download='spiro_review_candidates.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}finally{el('export').textContent='↓ Export candidates';busy(false);if(state.refreshPending){state.refreshPending=false;loadActive();}}});
function trackingParams(includePage=false){const q=new URLSearchParams();for(const key of ['country','start','end'])if(state.filters[key])q.set(key,state.filters[key]);q.set('group',tracking.group);if(includePage){q.set('limit','50');if(tracking.cursors[tracking.index])q.set('cursor',tracking.cursors[tracking.index]);}return q;}
function trackingEmpty(message){const tr=node('tr');const td=node('td','empty-state',message);td.colSpan=8;tr.append(td);el('gap-rows').replaceChildren(tr);}
function renderTracking(){
  const groups=tracking.summary.groups;for(const key of Object.keys(groupInfo)){el('count-'+key).textContent=number(groups[key].count);el('group-'+key).setAttribute('aria-pressed',String(key===tracking.group));el('group-'+key).classList.toggle('selected',key===tracking.group);const countries=el('countries-'+key);if(countries)countries.textContent=Object.entries(groups[key].by_country).map(([name,count])=>name+' '+number(count)).join(' · ')||'No records in this selection';}
  const info=groupInfo[tracking.group];el('gap-table-title').textContent=info.title;el('gap-caption').textContent=info.caption;el('gap-group').value=tracking.group;
  const records=tracking.page.records;el('gap-rows').replaceChildren();if(!records.length)trackingEmpty('No records in this group match the selected country and dates.');
  for(const r of records){const wallet=r.record_type==='Wallet deduction';const tr=node('tr');const customer=node('td');customer.append(node('div','customer-name',r.customer_name||'Customer unavailable'),node('div','cell-sub',r.customer_reference||r.mapped_customer_references?.join(', ')||r.customer_id||'No customer reference'));const country=node('td');country.append(node('span','country-chip',r.country||'Unknown'));const ref=node('td');const reference=r.wallet_reference||r.swap_reference||r.record_id;const primary=node('div','reference',reference);primary.title=reference;ref.append(primary,node('div','cell-sub',r.transaction_id?.trim()?r.transaction_id:'No Transaction ID'));const amount=node('td','amount-column');amount.append(node('span','amount',money(wallet?r.wallet_amount:r.swap_amount)),node('span','amount-currency',r.currency||'?'));const reason=node('td');reason.append(node('span','badge',gapReasons[r.missing_counterpart_reason]||r.missing_counterpart_reason));const method=node('td');method.append(node('div','',wallet?'Wallet debit':r.payment_method||'Payment method unavailable'),node('div','cell-sub',wallet?r.wallet_status:r.swap_status));const date=node('td','',sourceTime(r.created_on));const action=node('td');const open=node('button','open-button','View ↗');open.setAttribute('aria-label','View '+r.record_type.toLowerCase()+' '+reference);open.addEventListener('click',()=>openTrackingDetail(r));action.append(open);tr.append(customer,country,ref,amount,reason,method,date,action);el('gap-rows').append(tr);}
  const from=records.length?tracking.index*50+1:0;const to=records.length?tracking.index*50+records.length:0;el('gap-page-info').textContent=`Showing ${number(from)}–${number(to)} of ${number(groups[tracking.group].count)}`;
}
async function loadTracking(){
  if(tracking.busy){tracking.refreshPending=true;return;}tracking.busy=true;syncControls();error();el('updated').textContent='Refreshing…';el('gap-caption').textContent='Checking loaded transactions…';
  try{const data=await api('/api/counterparts?'+trackingParams(true));tracking.summary=data.summary;tracking.page=data.page;tracking.failed=false;renderTracking();el('updated').textContent='Refreshed '+new Date(data.generated_at_utc).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
  catch(e){tracking.failed=true;tracking.page=null;tracking.summary=null;error(e.message);el('updated').textContent='Refresh failed';for(const key of Object.keys(groupInfo)){el('count-'+key).textContent='—';const countries=el('countries-'+key);if(countries)countries.textContent='Results unavailable';}el('gap-caption').textContent='Use Refresh results to retry.';trackingEmpty('The tracking results could not be loaded. Please retry.');el('gap-page-info').textContent='Results unavailable';}
  finally{tracking.busy=false;syncControls();if(tracking.refreshPending){tracking.refreshPending=false;loadActive();}}
}
// Keep the shared workspace separate from its reconciliation modules.
const viewInfo={
  home:{title:'Home',eyebrow:'SPIRO OPERATIONS / WORKSPACE',description:'Your shared workspace for dashboards and operational reviews.'},
  overview:{title:'Wallet & swap reconciliation',eyebrow:'SWAP / WALLET & SWAP',description:'Track wallet deductions and investigate transactions that need attention.'},
  counterparts:{title:'Missing counterparts',eyebrow:'SWAP / MISSING COUNTERPARTS',description:'Investigate wallet deductions and swaps without a verified counterpart.'},
  due:{title:'Swap to Due',eyebrow:'SWAP / SWAP TO DUE',description:'Track due-created swaps and verify their repayment evidence.'},
  offer:{title:'Swap to Offer',eyebrow:'SWAP / SWAP TO OFFER',description:'Verify offer coverage using consumption and allocation evidence.'}
};
function selectView(view){
  if(!viewInfo[view]||state.busy||tracking.busy||due.busy||offers.busy)return;
  closeDetail();currentView=view;error();
  el('swap-navigation').classList.toggle('has-active',view!=='home');
  if(view!=='home')el('swap-navigation').open=true;
  for(const [name,id] of [['home','home-content'],['overview','overview-content'],['counterparts','gap-content'],['due','due-content'],['offer','offer-content']])el(id).hidden=name!==view;
  for(const id of ['filters','source-note','results-toolbar'])el(id).hidden=view==='home';
  document.querySelector('.status-filter').hidden=view!=='overview';
  for(const name of Object.keys(viewInfo)){
    const button=el('view-'+name);const selected=name===view;
    button.setAttribute('aria-pressed',String(selected));button.classList.toggle('active',selected);
    if(selected)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');
  }
  const info=viewInfo[view];el('page-title').textContent=info.title;el('page-eyebrow').textContent=info.eyebrow;el('page-description').textContent=info.description;
  document.title='Spiro | '+info.title;el('module-context').textContent=info.eyebrow.replace('SWAP / ','');
  el('status').value='';delete state.filters.status;resetPages();window.scrollTo(0,0);loadActive();
}
for(const name of Object.keys(viewInfo))el('view-'+name).addEventListener('click',()=>selectView(name));
for(const button of document.querySelectorAll('[data-open-view]'))button.addEventListener('click',()=>selectView(button.dataset.openView));
el('refresh-results').addEventListener('click',()=>{resetPages();loadActive();loadSources();});
el('overview-open-swaps').addEventListener('click',()=>{tracking.group='open_swaps';selectView('counterparts');});el('overview-paid-dues').addEventListener('click',()=>{due.group='resolved';el('due-group').value='resolved';selectView('due');});
el('overview-offers').addEventListener('click',()=>{offers.group='resolved';selectView('offer');});
function selectGroup(group){if(state.busy||tracking.busy)return;tracking.group=group;tracking.cursors=[null];tracking.index=0;loadTracking();}
for(const group of Object.keys(groupInfo))el('group-'+group).addEventListener('click',()=>selectGroup(group));el('gap-group').addEventListener('change',()=>selectGroup(el('gap-group').value));
el('gap-next').addEventListener('click',()=>{if(tracking.busy||!tracking.page?.has_more)return;tracking.cursors[tracking.index+1]=tracking.page.next_cursor;tracking.index++;loadTracking();});el('gap-previous').addEventListener('click',()=>{if(tracking.busy||!tracking.index)return;tracking.index--;loadTracking();});
function openTrackingDetail(r){
  state.returnFocus=document.activeElement;state.selected=r;el('drawer').hidden=false;el('drawer-overlay').hidden=false;el('close-drawer').focus();const body=el('drawer-content');body.replaceChildren(node('h2','',r.customer_name||r.record_type+' details'),node('span','badge',gapReasons[r.missing_counterpart_reason]||r.missing_counterpart_reason));const wallet=r.record_type==='Wallet deduction';let grid=node('dl','detail-grid');field(grid,'Country',r.country);field(grid,'Customer reference',r.customer_reference||r.mapped_customer_references);field(grid,'Customer ID',r.customer_id);field(grid,'Wallet',wallet?r.wallet_code||r.wallet_id:r.mapped_wallet_record_ids);body.append(node('h3','','Customer & wallet'),grid);
  grid=node('dl','detail-grid');field(grid,'Reference',r.wallet_reference||r.swap_reference);field(grid,'Transaction ID',r.transaction_id?.trim()||'Missing — cannot match by reference');field(grid,'Record ID',r.record_id);field(grid,'Amount',money(wallet?r.wallet_amount:r.swap_amount)+' '+(r.currency||'Unknown currency'));field(grid,'Created on',sourceTime(r.created_on));field(grid,'Status',r.wallet_status||r.swap_status);if(wallet){field(grid,'Transaction type',r.transaction_type);field(grid,'Settled against',r.settled_against);}else{field(grid,'Payment method',r.payment_method);field(grid,'Successful wallet payment',r.wallet_payment_expected?'Yes':'No');field(grid,'Station',r.station_label||r.station_code);field(grid,'Vehicle',r.vehicle_registration);field(grid,'Swap date',sourceTime(r.swap_date));field(grid,'Currency candidates',r.currency_candidates);}body.append(node('h3','',r.record_type),grid);
  grid=node('dl','detail-grid');field(grid,'Source file',r.source_file);field(grid,'Source row',r.source_row_number);field(grid,'Date context',r.date_context?.replaceAll('_',' '));field(grid,'First loaded counterpart',sourceTime(r.observed_first_swap||r.observed_first_wallet_deduction));field(grid,'Last loaded counterpart',sourceTime(r.observed_last_swap||r.observed_last_wallet_deduction));body.append(node('h3','','Source coverage'),grid,node('p','detail-note','Results reflect loaded exports. Missing identifiers prevent matching; a non-wallet swap may legitimately have no wallet deduction. Source completeness and any refund decision still need investigation.'));
}
el('gap-export').addEventListener('click',async()=>{if(tracking.busy||tracking.failed)return;tracking.busy=true;syncControls();error();el('gap-export').textContent='Exporting…';try{const response=await fetch('/api/counterparts/export?'+trackingParams());if(!response.ok){const data=await response.json();throw new Error(data.error||'Export failed.');}const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download=tracking.group+'_tracking.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}finally{el('gap-export').textContent='↓ Export group';tracking.busy=false;syncControls();if(tracking.refreshPending){tracking.refreshPending=false;loadActive();}}});
function dueParams(includePage=false){const q=new URLSearchParams();for(const key of ['country','start','end'])if(state.filters[key])q.set(key,state.filters[key]);q.set('group',due.group);if(includePage){q.set('limit','50');if(due.cursors[due.index])q.set('cursor',due.cursors[due.index]);}return q;}
function dueEmpty(message){const tr=node('tr');const td=node('td','empty-state',message);td.colSpan=9;tr.append(td);el('due-rows').replaceChildren(tr);}
function renderDue(){
  const s=due.summary;if(s.resolved_count===undefined)throw new Error('Stop the current PyCharm run and run main.py again to activate Paid Due resolutions.');el('due-total').textContent=number(s.swap_count);el('due-matched').textContent=number(s.resolved_count);el('due-review').textContent=number(s.needs_review_count);el('due-pending').textContent=number(s.pending_count);el('due-case-count').textContent=number(s.by_group[due.group]);el('due-group').value=due.group;el('due-caption').textContent=dueGroupInfo[due.group];
  el('due-countries').replaceChildren();if(!s.groups.length)el('due-countries').append(node('div','country-placeholder','No due-created swaps match these filters.'));
  for(const g of s.groups){const card=node('article','country-card');const top=node('div','country-top');top.append(node('span','country-icon',g.country==='Kenya'?'KE':'RW'));const title=node('div');title.append(node('h3','',g.country),node('div','currency-label',g.currency?g.currency+' · current wallet snapshot':g.currency_source==='ambiguous_wallet_snapshot'?'Currency differs across wallets':'Currency unavailable'));top.append(title);const value=node('div','rate',money(g.swap_amount));value.append(node('span','','recorded swap amount'));top.append(value);const stats=node('div','country-stats');stats.append(node('span','',number(g.swap_count)+' swaps'),node('span','',number(g.resolved_count)+' cleared by Paid Dues'),node('span','',number(g.needs_review_count)+' review'));card.append(top,stats);card.append(node('p','upload-dates','Linked Dues: Paid '+number(g.paid_count)+' · Pending '+number(g.pending_count)+' · Closed '+number(g.closed_count)));const source=s.due_sources?.find(item=>item.country===g.country);if(source){card.append(node('p','upload-dates','Loaded Dues (all dates): '+number(source.record_count)),node('p','upload-dates','Source status: Paid '+number(source.paid_count)+' · Pending '+number(source.pending_count)+' · Closed '+number(source.closed_count)));if(source.missing_swap_lookup_count)card.append(node('p','upload-warning',number(source.missing_swap_lookup_count)+' Due records have no swap lookup and cannot be matched automatically.'));if(source.export_limit_reached)card.append(node('p','upload-warning','A Due file reached the 200,000-row export limit. Verify coverage using the remaining date batches.'));}if(g.awaiting_due_export_count)card.append(node('p','upload-warning',number(g.awaiting_due_export_count)+' open swaps awaiting a '+g.country+' Due export.'));if(g.missing_amount_count)card.append(node('p','upload-warning',number(g.missing_amount_count)+' swaps have no amount and are excluded from this sum.'));el('due-countries').append(card);}
  el('due-coverage').textContent=s.awaiting_due_export_count?number(s.awaiting_due_export_count)+' swaps await a Due export for their country and remain open for review.':'Due matching reflects loaded exports. Source completeness still needs verification.';
  el('due-rows').replaceChildren();const records=due.page.records;if(!records.length)dueEmpty('No due-created swaps match the selected country and dates.');
  for(const r of records){const tr=node('tr');const customer=node('td');customer.append(node('div','customer-name',r.customer_name||'Customer unavailable'),node('div','cell-sub',r.customer_references?.join(', ')||r.customer_id||'No customer reference'));const country=node('td');country.append(node('span','country-chip',r.country));const ref=node('td');const reference=node('div','reference',r.swap_reference||r.record_id);reference.title=reference.textContent;ref.append(reference,node('div','cell-sub',r.swap_status||'Swap status unavailable'));const amount=node('td','amount-column');amount.append(node('span','amount',money(r.swap_amount)),node('span','amount-currency',r.currency||'?'));const dueRef=node('td','reference',r.due_reference|| (r.due_count>1?r.due_count+' Due records':'—'));const result=node('td');result.append(node('span','badge'+(r.due_record_status==='matched'?' good':''),dueResultLabels[r.due_record_status]||r.due_record_status));result.append(node('div','reason-sub',resolutionLabels[r.resolution_status]||'Needs review'));const status=node('td');status.append(node('span','badge'+(r.due_status==='Paid'?' good':''),r.due_status||(r.due_count>1?'Ambiguous':'Not available')));const action=node('td');const open=node('button','open-button','View ↗');open.setAttribute('aria-label','View due-created swap '+(r.swap_reference||r.record_id));open.addEventListener('click',()=>openDueDetail(r));action.append(open);tr.append(customer,country,ref,amount,dueRef,result,status,node('td','',sourceTime(r.created_on)),action);el('due-rows').append(tr);}
  const from=records.length?due.index*50+1:0;const to=records.length?due.index*50+records.length:0;el('due-page-info').textContent=`Showing ${number(from)}–${number(to)} of ${number(s.by_group[due.group])}`;
}
async function loadDue(){
  if(due.busy){due.refreshPending=true;return;}due.busy=true;syncControls();error();el('updated').textContent='Refreshing…';
  try{const data=await api('/api/due-swaps?'+dueParams(true));due.summary=data.summary;due.page=data.page;due.failed=false;renderDue();el('updated').textContent='Refreshed '+new Date(data.generated_at_utc).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
  catch(e){due.failed=true;due.page=null;due.summary=null;error(e.message);el('updated').textContent='Refresh failed';for(const id of ['due-total','due-matched','due-review','due-pending','due-case-count'])el(id).textContent='—';el('due-countries').replaceChildren(node('div','country-placeholder','Results unavailable. Use Refresh results to retry.'));el('due-coverage').textContent='Results unavailable';dueEmpty('Due-created swaps could not be loaded. Please retry.');el('due-page-info').textContent='Results unavailable';}
  finally{due.busy=false;syncControls();if(due.refreshPending){due.refreshPending=false;loadActive();}}
}
function openDueDetail(r){
  state.returnFocus=document.activeElement;state.selected=r;el('drawer').hidden=false;el('drawer-overlay').hidden=false;el('close-drawer').focus();const body=el('drawer-content');body.replaceChildren(node('h2','',r.customer_name||'Due-created swap'),node('span','badge'+(r.due_record_status==='matched'?' good':''),dueResultLabels[r.due_record_status]||r.due_record_status));
  let grid=node('dl','detail-grid');for(const [label,value] of [['Country',r.country],['Customer references',r.customer_references],['Customer ID',r.customer_id]])field(grid,label,value);body.append(node('h3','','Customer'),grid);
  grid=node('dl','detail-grid');for(const [label,value] of [['Swap reference',r.swap_reference],['Record ID',r.record_id],['Transaction ID',r.transaction_id||'Not supplied'],['Payment method',r.payment_method],['Swap status',r.swap_status],['Swap amount',money(r.swap_amount)+' '+(r.currency||'Unknown currency')],['Currency source',r.currency_source.replaceAll('_',' ')],['Created on',sourceTime(r.created_on)],['Swap date',r.swap_date],['Station',r.station],['Vehicle',r.vehicle_registration]])field(grid,label,value);body.append(node('h3','','Swap'),grid);
  grid=node('dl','detail-grid');field(grid,'Linked Due records',r.due_count);field(grid,'Match result',dueResultLabels[r.due_record_status]||r.due_record_status);field(grid,'Due status',r.due_status||r.repayment_status);field(grid,'Review resolution',resolutionLabels[r.resolution_status]||'Needs review');field(grid,'Attached wallet debits',r.wallet_debit_count);field(grid,'Swap source file',r.source_file);field(grid,'Source row',r.source_row_number);body.append(node('h3','','Due reconciliation'),grid);
  for(const d of r.dues){grid=node('dl','detail-grid');for(const [label,value] of [['Due reference',d.reference],['Due Record ID',d.record_id],['Customer ID',d.customer_id],['Due amount',money(d.amount)+' '+(d.currency||'Unknown currency')],['Original Due amount',money(d.original_amount)],['Due type',d.type],['Status (Zoho)',d.status],['Payment mode',d.payment_mode],['Settlement Transaction ID',d.transaction_id],['Due creation date',d.creation_date],['Settlement date',d.settlement_date],['Source modified',sourceTime(d.source_modified_at)],['Due source file',d.source_file]])field(grid,label,value);body.append(node('h3','','Due '+(d.reference||d.record_id)),grid);}
  body.append(node('p','detail-note','Links use the Due’s exact swap lookup and country. Paid, Pending and Closed reflect the source export; Closed does not establish repayment. Due Amount can remain populated on Paid records and is not a verified outstanding balance.'));
}
el('due-group').addEventListener('change',()=>{due.group=el('due-group').value;due.cursors=[null];due.index=0;loadDue();});
el('due-next').addEventListener('click',()=>{if(due.busy||!due.page?.has_more)return;due.cursors[due.index+1]=due.page.next_cursor;due.index++;loadDue();});el('due-previous').addEventListener('click',()=>{if(due.busy||!due.index)return;due.index--;loadDue();});
el('due-export').addEventListener('click',async()=>{if(due.busy||due.failed||!due.page)return;due.busy=true;syncControls();error();el('due-export').textContent='Exporting…';try{const response=await fetch('/api/due-swaps/export?'+dueParams());if(!response.ok){const data=await response.json();throw new Error(data.error||'Export failed.');}const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download='spiro_due_'+due.group+'.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}finally{el('due-export').textContent='↓ Export group';due.busy=false;syncControls();if(due.refreshPending){due.refreshPending=false;loadActive();}}});

function offerParams(paging=false){const q=new URLSearchParams();for(const key of ['country','start','end'])if(state.filters[key])q.set(key,state.filters[key]);q.set('group',offers.group);if(paging){q.set('limit','50');if(offers.cursors[offers.index])q.set('cursor',offers.cursors[offers.index]);}return q;}
function offerEmpty(message){const tr=node('tr');const td=node('td','empty-state',message);td.colSpan=8;tr.append(td);el('offer-rows').replaceChildren(tr);}
function renderOffers(){const s=offers.summary;for(const [id,key] of [['total','swap_count'],['resolved','resolved_count'],['review','needs_review_count'],['wallet','wallet_attached_count']])el('offer-'+id).textContent=number(s[key]);el('offer-case-count').textContent=number(s.by_group[offers.group]);el('offer-group').value=offers.group;
  el('offer-countries').replaceChildren();for(const c of s.by_country){const card=node('article','country-card');card.append(node('h3','',c.country));const stats=node('div','country-stats');for(const [label,key] of [['Offer swaps','swap_count'],['Cleared','resolved_count'],['Review','needs_review_count']]){const text=node('span','',label+' ');text.append(node('b','',number(c[key])));stats.append(text);}card.append(stats,node('p','upload-dates',number(c.wallet_attached_count)+' already have wallet deductions'));el('offer-countries').append(card);}if(!s.by_country.length)el('offer-countries').append(node('div','country-placeholder','No offer swaps match these filters.'));
  el('offer-sources').textContent=s.sources.map(r=>r.country+' '+r.module+': '+number(r.rows)+(r.missing_lookup_rows?' · '+number(r.missing_lookup_rows)+' missing lookups':'')).join(' | ')||'No offer exports loaded. Add allocation and consumption CSVs above.';el('offer-reasons').textContent=Object.entries(s.review_reasons).map(([reason,count])=>(offerLabels[reason]||reason)+': '+number(count)).join(' · ')||'No offer swaps need review in this selection.';
  el('offer-rows').replaceChildren();for(const r of offers.page.records){const tr=node('tr');const customer=node('td');customer.append(node('div','customer-name',r.customer_name||'Customer unavailable'),node('div','cell-sub',r.business_id||r.customer_id||'No customer reference'));const ref=node('td');ref.append(node('div','reference',r.swap_reference||r.record_id),node('div','cell-sub',r.swap_status));const result=node('td');result.append(node('span','badge'+(r.resolution_status==='resolved_offer'?' good':''),offerResolution[r.resolution_status]),node('div','reason-sub',offerLabels[r.offer_result]||r.offer_result));const action=node('td');const button=node('button','open-button','View ↗');button.setAttribute('aria-label','View offer swap '+(r.swap_reference||r.record_id));button.addEventListener('click',()=>openOfferDetail(r));action.append(button);tr.append(customer,node('td','',r.country),ref,node('td','reference',r.allocation_reference||'—'),node('td','',money(r.consumed_soc)+' / '+money(r.net_soc)),result,node('td','',sourceTime(r.created_on)),action);el('offer-rows').append(tr);}if(!offers.page.records.length)offerEmpty('No offer swaps in this result group.');const count=offers.page.records.length;el('offer-page-info').textContent=`Showing ${count?offers.index*50+1:0}–${count?offers.index*50+count:0} of ${number(s.by_group[offers.group])}`;el('offer-caption').textContent=offers.group==='resolved'?'Verified full SOC coverage; these swaps leave the open swap review.':'Inspect the linked consumption and allocation for each swap.';
}
async function loadOffers(){if(offers.busy){offers.refreshPending=true;return;}offers.busy=true;syncControls();error();el('updated').textContent='Refreshing…';try{const data=await api('/api/offer-swaps?'+offerParams(true));offers.summary=data.summary;offers.page=data.page;offers.failed=false;renderOffers();el('updated').textContent='Refreshed '+new Date(data.generated_at_utc).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){offers.failed=true;offers.page=null;offers.summary=null;error(e.message);for(const id of ['total','resolved','review','wallet','case-count'])el('offer-'+id).textContent='—';el('offer-countries').replaceChildren();el('offer-sources').textContent='Results unavailable';el('offer-reasons').textContent='';offerEmpty('Offer results could not be loaded. Restart main.py if this view was just added.');el('offer-page-info').textContent='Results unavailable';el('updated').textContent='Refresh failed';}finally{offers.busy=false;syncControls();if(offers.refreshPending){offers.refreshPending=false;loadActive();}}}
function openOfferDetail(r){state.returnFocus=document.activeElement;state.selected=r;el('drawer').hidden=false;el('drawer-overlay').hidden=false;el('close-drawer').focus();const body=el('drawer-content');body.replaceChildren(node('h2','',r.customer_name||'Offer swap'),node('span','badge'+(r.resolution_status==='resolved_offer'?' good':''),offerResolution[r.resolution_status]),node('p','',offerLabels[r.offer_result]||r.offer_result));let grid=node('dl','detail-grid');for(const [label,value] of [['Country',r.country],['Customer ID',r.customer_id],['Customer reference',r.business_id],['Swap reference',r.swap_reference],['Swap Record ID',r.record_id],['Swap created',sourceTime(r.created_on)],['Swap amount',money(r.swap_amount)+' '+(r.currency||'?')],['Net SOC',money(r.net_soc)],['Billable SOC',money(r.billable_soc)],['Non-billable SOC',money(r.non_billable_soc)],['Attached wallet debits',r.wallet_debit_count],['Source file',r.source_file],['Source row',r.source_row_number]])field(grid,label,value);body.append(node('h3','','Swap'),grid);
  for(const c of r.consumptions){grid=node('dl','detail-grid');for(const [label,value] of [['Record ID',c.zoho_record_id],['Reference',c.consumption_reference],['Swap lookup',c.swap_record_id],['Allocation reference',c.allocation_reference],['Customer reference',c.customer_business_id],['Currency',c.currency],['Consumption date',c.consumption_date],['Offer name',c.offer_name],['Allocated SOC',c.allocated_soc],['Consumed SOC',c.consumed_soc],['Remaining SOC',c.remaining_soc],['Consumed discount',c.consumed_discount],['Source file',c.source_file],['Source row',c.source_row_number]])field(grid,label,value);body.append(node('h3','','Consumption'),grid);}
  for(const a of r.allocations){grid=node('dl','detail-grid');for(const [label,value] of [['Record ID',a.zoho_record_id],['Allocation reference',a.allocation_reference],['Customer ID',a.customer_id],['Offer reference',a.offer_reference],['Offer lookup',a.offer_id],['Type',a.offer_type],['Frequency',a.frequency],['Current status',a.status],['Allocation date',a.allocation_date],['Valid from',a.valid_from],['Valid till',a.valid_till],['Expiry date',a.expiry_date],['Total SOC',a.total_soc],['Consumed SOC',a.consumed_soc],['Loaded consumption SOC',r.loaded_consumed_soc],['Source file',a.source_file],['Source row',a.source_row_number]])field(grid,label,value);body.append(node('h3','','Allocation'),grid);}body.append(node('p','detail-note','Resolution checks use exact source links and full SOC voucher coverage. Allocation status is a current snapshot; historical use still needs valid dates. Conflicts remain open for investigation.'));}
el('offer-group').addEventListener('change',()=>{offers.group=el('offer-group').value;offers.cursors=[null];offers.index=0;loadOffers();});el('offer-next').addEventListener('click',()=>{if(offers.busy||!offers.page?.has_more)return;offers.cursors[offers.index+1]=offers.page.next_cursor;offers.index++;loadOffers();});el('offer-previous').addEventListener('click',()=>{if(offers.busy||!offers.index)return;offers.index--;loadOffers();});
el('offer-export').addEventListener('click',async()=>{if(offers.busy||offers.failed||!offers.page)return;offers.busy=true;syncControls();error();try{const response=await fetch('/api/offer-swaps/export?'+offerParams());if(!response.ok){const data=await response.json();throw new Error(data.error||'Export failed.');}const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download='spiro_offer_'+offers.group+'.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}finally{offers.busy=false;syncControls();if(offers.refreshPending){offers.refreshPending=false;loadActive();}}});

loadActive();

const uploads = {token:null,maxBytes:512*1024*1024,busy:false,jobs:[]};
function uploadError(message){el('upload-error').hidden=!message;el('upload-error').textContent=message||'';}
function uploadControls(){el('upload-files').disabled=uploads.busy;el('validate-files').disabled=uploads.busy||!uploads.token||!el('upload-files').files.length||uploads.jobs.length>0;el('import-files').disabled=uploads.busy||!uploads.jobs.some(job=>job.state==='ready');el('clear-files').disabled=uploads.busy||(!uploads.jobs.length&&!el('upload-files').files.length);}
async function importAction(path,body,headers={}){const response=await fetch(path,{method:'POST',headers:{'X-Spiro-Token':uploads.token,...headers},body});const data=await response.json();if(!response.ok){const failure=new Error(data.error||'The import request failed.');failure.status=response.status;throw failure;}return data;}
function renderJobs(){el('upload-jobs').replaceChildren();for(const job of uploads.jobs){const card=node('article','upload-card');const head=node('div','upload-card-head');head.append(node('strong','upload-filename',job.filename),node('span','upload-state '+job.state,job.state==='ready'?'Validated':job.state==='complete'?'Imported':job.state==='failed'?'Failed':job.phase||job.state));card.append(head);if(job.preview){const p=job.preview;card.append(node('div','upload-meta',p.module+' · '+Object.entries(p.countries).map(([country,count])=>country+' '+number(count)).join(' · ')+' · '+number(p.rows)+' rows'));card.append(node('div','upload-dates','Created: '+sourceTime(p.min_created_on)+' → '+sourceTime(p.max_created_on)));if(p.duplicate_record_id_rows)card.append(node('p','upload-warning',number(p.duplicate_record_id_rows)+' repeated Record Id rows. The latest source version is kept.'));if(p.export_cap_warning)card.append(node('p','upload-warning','This file may be at the Zoho export limit. Add the remaining date batches to complete coverage.'));if(['due','offer_consumption'].includes(p.dataset)&&p.missing_swap_lookup_rows)card.append(node('p','upload-warning',number(p.missing_swap_lookup_rows)+' records have no swap lookup. They are saved, but cannot be matched to swaps automatically.'));}if(job.result)card.append(node('p','upload-result',number(job.result.rows_read)+' rows read · '+number(job.result.rows_applied)+' records added or updated'+(job.result.rows_applied===0?' · Already loaded or older than the current data.':'')));else if(job.processed_rows)card.append(node('p','upload-progress',number(job.processed_rows)+' rows processed'));if(job.warning)card.append(node('p','upload-warning',job.warning));if(job.error)card.append(node('p','upload-failure',job.error));el('upload-jobs').append(card);}uploadControls();}
async function waitForImport(job){while(['receiving','validating','importing'].includes(job.state)){await new Promise(resolve=>setTimeout(resolve,1000));const update=await api('/api/import-jobs/'+job.id);Object.assign(job,update);renderJobs();}return job;}
async function loadSources(){try{const data=await api('/api/sources');el('source-inventory').replaceChildren();for(const [dataset,title]of [['wallet_master','Wallets'],['wallet','Wallet transactions'],['swap','Swapping transactions'],['due','Dues'],['offer_allocation','Offer allocations'],['offer_consumption','Offer consumptions']]){const card=node('article','source-card');card.append(node('h3','',title));const rows=data.sources.filter(row=>row.dataset===dataset);if(!rows.length)card.append(node('p','','No data loaded'));for(const row of rows){const line=node('div','source-count');line.append(node('span','',row.country||'Unknown country'),node('strong','',number(row.rows)));card.append(line);}el('source-inventory').append(card);}el('import-history').replaceChildren();if(!data.recent_imports.length)el('import-history').append(node('p','','No imports yet. Add your first export above.'));for(const batch of data.recent_imports){const line=node('div','history-row');const title=node('div');title.append(node('strong','',batch.filename),node('span','',batch.module+' · '+new Date(batch.imported_at).toLocaleString()));line.append(title,node('span','',number(batch.rows_read)+' read / '+number(batch.rows_applied)+' changed'));el('import-history').append(line);}}catch(e){el('source-inventory').replaceChildren(node('p','upload-failure',e.message));}}
el('upload-files').addEventListener('change',()=>{uploadError();uploadControls();el('upload-message').textContent=el('upload-files').files.length?el('upload-files').files.length+' file(s) selected. Validate them before importing.':'';});
el('validate-files').addEventListener('click',async()=>{const files=Array.from(el('upload-files').files);uploadError();if(!files.length)return;if(files.length>10){uploadError('Choose up to 10 files at a time.');return;}if(files.some(file=>!file.name.toLowerCase().endsWith('.csv')||!file.size||file.size>uploads.maxBytes)){uploadError('Choose nonempty CSV files up to 512 MB each.');return;}uploads.busy=true;uploadControls();try{for(const file of files){el('upload-message').textContent='Uploading and validating '+file.name+'…';const job=await importAction('/api/uploads',file,{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name)});uploads.jobs.push(job);renderJobs();await waitForImport(job);}const ready=uploads.jobs.filter(job=>job.state==='ready').length;el('upload-message').textContent=ready?ready+' file(s) validated. Review the details below, then click Import validated files.':'No files passed validation. Clear the list and choose a corrected export.';}catch(e){uploadError(e.message);el('upload-message').textContent='Validation stopped. Completed file checks are shown below.';}finally{uploads.busy=false;renderJobs();}});
el('import-files').addEventListener('click',async()=>{uploads.busy=true;uploadControls();uploadError();const order={wallet_master:0,wallet:1,swap:2,due:3,offer_allocation:4,offer_consumption:5};const ready=uploads.jobs.filter(job=>job.state==='ready').sort((a,b)=>order[a.preview.dataset]-order[b.preview.dataset]);let imported=0,importedDue=false,importedOffer=false;try{for(const job of ready){el('upload-message').textContent='Importing '+job.filename+'…';Object.assign(job,await importAction('/api/import-jobs/'+job.id+'/commit'));renderJobs();await waitForImport(job);if(job.state!=='complete')throw new Error(job.error||'Import failed.');imported++;if(job.preview.dataset==='due')importedDue=true;if(job.preview.dataset.startsWith('offer_'))importedOffer=true;}el('upload-message').textContent=imported+' file(s) imported. '+(importedOffer?'Offer coverage refreshes the open swap counts and Swap to Offer.':importedDue?'Paid Due resolutions refresh the swap review counts on the overview and in Swap to Due.':'Reconciliation results refresh automatically below.');}catch(e){uploadError(e.message);el('upload-message').textContent=imported+' file(s) confirmed imported. Earlier completed files are saved. Check Recent imports if the connection was interrupted.';}finally{uploads.busy=false;renderJobs();await loadSources();if(imported){resetPages();if(importedOffer&&!state.busy&&!tracking.busy&&!due.busy&&!offers.busy)selectView('offer');else if(importedDue&&!state.busy&&!tracking.busy&&!due.busy&&!offers.busy)selectView('due');else loadActive();}}});
el('clear-files').addEventListener('click',async()=>{uploads.busy=true;uploadControls();try{for(const job of uploads.jobs){try{await importAction('/api/import-jobs/'+job.id+'/discard');}catch(e){if(e.status!==404)throw e;}}uploads.jobs=[];el('upload-files').value='';el('upload-message').textContent='';uploadError();}catch(e){uploadError(e.message);}finally{uploads.busy=false;renderJobs();}});
el('refresh-sources').addEventListener('click',loadSources);
el('import-panel').addEventListener('toggle',()=>{document.querySelector('.import-open').textContent=el('import-panel').open?'Close ↑':'Open ↓';});
(async()=>{try{const session=await api('/api/session');uploads.token=session.csrf_token;uploads.maxBytes=session.max_upload_bytes;uploadControls();}catch(e){uploadError('File uploads are unavailable. Refresh the dashboard.');}loadSources();})();
